dependencies:
- name: aya-day-weather-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.21
- name: aya-day-weather-proxy
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
